### ISSUE TITLE
Error from labadmin plugin prompt, after I had problems in reaching HA Ui 

### ISSUE THREAD

**Issue by vongomben** [matjack1/hassio-labadmin#2]
`utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/djangolabadmin/settings.py", line 23
    SECRET_KEY = 'row7ak8hrs(#7)oaty^SECRET_KEY = '***' # SECRET_KEY0o=v13u3(%c#k(d*!zlSECRET_KEY = '***' # SECRET_KEYz0ruc4_6)s', # SECRET_KEY
                                                     ^
SyntaxError: invalid syntax
[2019-02-26 18:26:35 +0100] [22] [INFO] Starting gunicorn 19.9.0
[2019-02-26 18:26:35 +0100] [22] [INFO] Listening at: http://0.0.0.0:8000 (22)
[2019-02-26 18:26:35 +0100] [22] [INFO] Using worker: sync
[2019-02-26 18:26:35 +0100] [25] [INFO] Booting worker with pid: 25
[2019-02-26 18:26:35 +0100] [26] [INFO] Booting worker with pid: 26
[2019-02-26 18:26:37 +0100] [25] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/www/djangolabadmin/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/www/djangolabadmin/settings.py", line 23
    SECRET_KEY = 'row7ak8hrs(#7)oaty^SECRET_KEY = '***' # SECRET_KEY0o=v13u3(%c#k(d*!zlSECRET_KEY = '***' # SECRET_KEYz0ruc4_6)s', # SECRET_KEY
                                                     ^
SyntaxError: invalid syntax
[2019-02-26 18:26:37 +0100] [25] [INFO] Worker exiting (pid: 25)
[2019-02-26 18:26:37 +0100] [26] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/www/djangolabadmin/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/www/djangolabadmin/settings.py", line 23
    SECRET_KEY = 'row7ak8hrs(#7)oaty^SECRET_KEY = '***' # SECRET_KEY0o=v13u3(%c#k(d*!zlSECRET_KEY = '***' # SECRET_KEYz0ruc4_6)s', # SECRET_KEY
                                                     ^
SyntaxError: invalid syntax
[2019-02-26 18:26:37 +0100] [26] [INFO] Worker exiting (pid: 26)
[2019-02-26 18:26:37 +0100] [22] [INFO] Shutting down: Master
[2019-02-26 18:26:37 +0100] [22] [INFO] Reason: Worker failed to boot.`

**Comment by matjack1** [comment]
This is now fixed here: https://github.com/OfficineArduinoTorino/docker-labadmin I've stripped some potentially dangerous characters in the `SECRET_KEY` variable
